{{include file='_admin/form_errors.phtml'/}}
<div class='tabs'>

  <ul>
    <li id='properties'><a href="#">Свойства</a></li>
    <li id='description'><a href="#">Аннотация</a></li>
    <li id='content'><a href="#">Текст</a></li>
  </ul>

  <div id="tab_properties">
    <?php if(!$this->item->isRoot()): ?>
      <dl class="required field">
        <dt><label for="identifier">Идентификатор:</label></dt>
        <dd>{{input type="text" name="identifier" id="identifier" title="Идентификатор"/}}</dd>
      </dl>
    <?php endif; ?>

    <dl class="required field">
      <dt><label for="title">Заголовок:</label></dt>
      <dd>{{input type="text" name="title" id="title" title="Заголовок"/}}</dd>
    </dl>

    <dl class="field">
      <dt><label for="keywords">Ключевые слова:</label></dt>
      <dd>{{textarea name='keywords' title='Ключевые слова' rows="2" cols="40"/}}</dd>
    </dl>
  </div>
  <div id="tab_description">
    {{wysiwyg id='description' name='description' width='100%' height='310' title="Аннотация"/}}
  </div>

  <div id="tab_content">
    {{wysiwyg id='content' name='content' width='100%' height='310' title="Контент"/}}
  </div>

</div>
{{include file='_admin/form_buttons.phtml'/}}