[[wrap with="admin_modal_page_layout.phtml" into="content_zone"]]
  [[form id='object_form' name='object_form' method='post' enctype="multipart/form-data" runat='server']]

    <h1>Редактирование {$#model_url} &laquo;[$#item.id]&raquo;</h1>

    [[include file='_admin/form_errors.phtml'/]]
    [[include file='admin_{$#model_url}/include/form_fields.phtml'/]]
    [[include file='_admin/form_buttons.phtml'/]]

  [[/form]]
[[/wrap]]