<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    {{list using="{$#column_names}" as="$column_name" parity='$parity'}}
      {{list:item}}
        <dl class="field">
          <dt>[[label for="{$column_name}"]]{$column_name}:[[/label]]</dt>
          <dd>{$#form_fields[$column_name]|raw}</dd>
        </dl>
      {{/list:item}}
    {{/list}}
  </div>

</div>