<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    {{list using="{$#column_names}" as="$column_name" parity='$parity'}}
    <table class='fieldset'>
      {{list:item}}
        <tr class="{$parity}">
          <td class="field_name">[[label for="{$column_name}"]]{$column_name}:[[/label]]</td>
          <td class="field_value">{$#form_fields[$column_name]|raw}</td>
          <td class="field_comment"></td>
        </tr>
      {{/list:item}}
    </table>
    {{/list}}
  </div>

</div>