<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<? $this->static_files_version = lmb_env_get('CMS_STATIC_FILES_VERSION'); ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp.css?{$#static_files_version}" />
  <!--[if IE]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie.css?{$#static_files_version}" /><![endif]-->
  <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie6.css?{$#static_files_version}" /><![endif]-->
  {{slot id='header_zone' /}}
  <style type="text/css">
    {{slot id='css_zone' /}}
  </style>
</head>
<body>
  <div id="popup_wrapper">
    {{include file='_admin/notify_zone.phtml'/}}
    {{slot id='icon'/}}
    {{slot id='title'/}}
    {{slot id='content_zone'/}}
  </div>
</body>
<script src="<? echo lmb_env_get('JQUERY_FILE_URL'); ?>?{$#static_files_version}"></script>
<script src="/shared/js/js/limb.js?{$#static_files_version}"></script>
<script src="/shared/js/js/limb/url.js?{$#static_files_version}"></script>
<script src="/shared/js/js/limb/flash.js?{$#static_files_version}"></script>
<script src="/shared/js/js/limb/window.js?{$#static_files_version}"></script>
<script src="/shared/js/js/limb/forms.js?{$#static_files_version}"></script>
<script src="/shared/js/js/limb/form_elements.js?{$#static_files_version}"></script>
<script src="/shared/cms/js/tabs.js?{$#static_files_version}"></script>
<script src="/shared/cms/js/auto_tabs.js?{$#static_files_version}"></script>
<script src="/shared/cms/js/thickbox.js?{$#static_files_version}"></script>
<script src="/shared/cms/js/cp.js?{$#static_files_version}"></script>
{{slot id='js_include'/}}

<script type="text/javascript">
  {{slot id='js'/}}

  jQuery(window).ready(function()
  {
    {{slot id='js_ready'/}}
  });
</script>
</html>
