{{wrap with="admin_page_layout.phtml"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  {{into slot="content_zone"}}
    <?php  $this->items->sort(array('url' => 'asc')) ?>
    <style>
    dl.cms_meta dt {font-weight: bold;}
    dl.cms_meta dd {font-size: 0.8em;}

    </style>
    <div id="header">
      <h1>Мета поля</h1>

      <div class="header_actions">
        <a href='{{route_url params="controller:admin_seo,action:create"/}}' title="Добавить элемент" class='thickbox'><img src='/shared/cms/images/icons/page_add.png' alt='Добавить'/> Добавить</a>
      </div>
    </div>

    <div id="body">
      {{list using='{$#items}' parity='{$parity}'}}
      {{include file="_admin_object/actions.phtml"/}}
      <div class="list">
        <table>
          <tr>
            <th>#ID</th>
            <th width='90%'>URL Metadata</th>
            <th>Действия</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>
              <td>{$item.id}</td>
              <td>
              <a href="{$item.url}" style="font-weight: bold;">{$item.url}</a>
              <dl class="cms_meta">
                <dt>Title</dt><dd>{$item.title}</dd>
                <dt>Keywords</dt><dd>{$item.keywords}</dd>
                <dt>Description</dt><dd>{$item.description}</dd>
              </dl>
              </td>
              <td class='actions'>
                {{apply template="object_action_edit" controller="admin_seo" item="{$item}"/}}
                {{apply template="object_action_delete" controller="admin_seo" item="{$item}"/}}
              </td>
            </tr>
            {{/list:item}}
            {{list:empty}}
              <div class="empty_list">Записи отсутствуют</div>
            {{/list:empty}}
          </table>
        </div>
      {{/list}}
    </div>
  {{/into}}
{{/wrap}}

