{{wrap with="admin_page_layout.phtml"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  {{into slot="content_zone"}}
    <div id="header">
      <h1>Мета-данные (SEO)</h1>

      <div class="header_actions">
        <a href='{{route_url params="controller:admin_seo,action:create"/}}' title="Добавить элемент" class='thickbox'><img src='/shared/cms/images/icons/page_white_add.png'/> Добавить элемент</a>
      </div>
    </div>

    <div id="body">
      <?php  $this->items->sort(array('url' => 'asc')); ?>
      {{list using='{$#items}' parity='{$parity}'}}
      {{include file="_admin_object/actions.phtml"/}}
      <div class="list">
        <table>
          <tr>
            <th>#ID</th>
            <th width='20%'>URL</th>
            <th width='20%'>Title</th>
            <th width='60%'>Metadata</th>
            <th>Действия</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>
              <td>#{$item.id}</td>
              <td><a href="{$item.url}" style="font-weight: bold;">{$item.url}</a></td>
              <td>{$item.title}</td>
              <td>
                <dl class="cms_meta">
                  <dt>Keywords</dt><dd>{$item.keywords}</dd>
                  <dt>Description</dt><dd>{$item.description}</dd>
                </dl>
              </td>
              <td class='actions'>
                {{apply template="object_action_edit" controller="admin_seo" item="{$item}" icon="page_white_edit" /}}
                {{apply template="object_action_delete" controller="admin_seo" item="{$item}" icon="page_white_delete" /}}
              </td>
            </tr>
            {{/list:item}}
            {{list:empty}}
              <div class="empty_list">Записи отсутствуют</div>
            {{/list:empty}}
          </table>
        </div>
      {{/list}}
    </div>
  {{/into}}

  {{into slot="css_zone"}}
    dl.cms_meta dt {font-size:0.9em;font-weight: bold;}
    dl.cms_meta dd {font-size: 0.8em;margin:0 0 3px;}
  {{/into}}

{{/wrap}}

