{{wrap with="front_page_layout.phtml"}}

  {{into slot="description"}}Карта сайта{{/into}}
  {{into slot="keywords"}}sitemap карта сайт limb{{/into}}
  {{into slot="title"}}Карта сайта{{/into}}

  {{into slot="content_zone"}}
    <h1>Карта сайта</h1>
    <div class="breadcrumbs"><a href="/">Начало</a>&nbsp;&raquo;&nbsp;Карта сайта</div>

    <?php

      lmb_require('limb/tree/src/lmbTreeNestedCollection.class.php');
      lmb_require('limb/tree/src/lmbTreeHelper.class.php');

      $docs = lmbActiveRecord::find('lmbCmsDocument', lmbSQLCriteria::equal('is_published', 1)->addAnd(new lmbSQLCriteria('level > 0')));
      $sorted_docs = lmbTreeHelper :: sort($docs, array('id' => 'ASC'));

      $processed_docs = new lmbTreeNestedCollection($sorted_docs);
      $processed_docs->setChildrenField('preloaded_children');
      $processed_docs->rewind();

    ?>
    {{tree using="$processed_docs" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
      <ul>
      {{tree:node}}
        <li><a href="{$item.uri}">{$item.title}</a>{{tree:nextlevel/}}</li>
      {{/tree:node}}
      </ul>
    {{/tree}}
  {{/into}}

{{/wrap}}



