{{wrap with="admin_modal_page_layout.phtml"}}

  {{into slot="content_zone"}}

    <h1>Предварительный просмотр текстового блока &laquo;{$#item.title}&raquo;</h1>

    <div class="actions">
      <a href='{{route_url params="action:edit,id:{$#item.identifier}"/}}' title="Редактирование"><img src='/shared/cms/images/icons/layout_edit.png'/> Редактировать</a>
    </div>

    <dl class="properties">
      <dt>Заголовок:</dt><dd>{$#item.title}</dd>
      <dt>Идентификатор:</dt><dd>{$#item.identifier}</dd>
      <dt>Содержимое:</dt><dd>&nbsp;</dd>
    </dl>

    {$#item.content|raw}

  {{/into}}

  {{into slot="css_zone"}}
    .properties dt {float:left;font-weight:bold;width:120px;}
    .properties dd {}

    .actions{float:right;}
    .actions a{font-weight:bold;}
        .actions a img{margin:0 0 0 -20px;vertical-align:middle;}
  {{/into}}

{{/wrap}}
