{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}

    <h1>Вы действительно хотите удалить следующие объекты?</h1>

      {{form method="post"}}
        {{list using='{$#items}'}}
          <div class="list">
            <table>
              <tr>
                <th class='selector'><input type='checkbox' onclick='toggle_selected(this);' name='mark_all'/></th>
                <th>Название</th>
              </tr>
              {{list:item}}
                <tr>
                  <td class='selector'><input type='checkbox' name="ids[]" value='{$item.id}' checked="checked"/></td>
                  <td>{$item.title}</td>
                </tr>
              {{/list:item}}
              {{list:empty}}
                <p>Вы ничего не отметили</p>
              {{/list:empty}}
            </table>
          </div>
        {{/list}}

        {{include file='_admin/form_buttons.phtml' save_button_name="Удалить"/}}

      {{/form}}

{{/wrap}}
