<div class='tabs'>
  <ul>
    <li id='properties'><a href="#">Свойства</a></li>
    <li id='content'><a href="#">Текст</a></li>
  </ul>

  <div id="tab_properties">

    <dl class="required field">
      <dt><label for="identifier">Идентификатор:</label></dt>
      <dd>{{input type="text" name="identifier" id="identifier" title="Идентификатор"/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="title">Название:</label></dt>
      <dd>{{input type="text" name="title" id="title" title="Название"/}}</dd>
    </dl>

  </div>

  <div id="tab_content">
    {{wysiwyg id='content' name='content' width='100%' height='310' title="Контент"/}}
  </div>

</div>