{{wrap with="_cms/popup.phtml" into="content_zone"}}

  {{form id='user_form' name='user_form' method='post' runat='server'}}

    <?php $this->editing_user= lmbActiveRecord::findById('lmbCmsUser',$this->request->get('id'));?>
    <h1>Изменение пароля пользователя:{$#editing_user.login} - {$#editing_user.name} </h1>

    {{include file='_cms/form_errors.phtml'/}}

    <div class='tabs'>

      <ul class="bookmarks">
        <li id='properties_link'><a>Свойства</a></li>
      </ul>

      <div id="tab_properties" class='bookmarks_content'>

          <div class='field'>
            {{label for="password" errorclass='error_label'}}Новый пароль:{{/label}}
            {{input name="password" type="password" title="Новый пароль" class='input'/}}
          </div>

          <div class='field'>
            {{label for="repeat_password" errorclass='error_label'}}Подтверждение пароля:{{/label}}
            {{input name="repeat_password" type="password" title="Подтверждение пароля" class='input'/}}
          </div>

      </div>

    </div>

    <div class='form_buttons'>
      {{input type="submit" name="submitted" class='button' value="Изменить пароль пользователя"/}}
    </div>

  {{/form}}


{{/wrap}}

