{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}

  {{form id='user_form' name='user_form' method='post' runat='server'}}

    <?php $this->editing_user= lmbActiveRecord::findById('lmbCmsUser',$this->request->get('id'));?>
    <h1>Изменение пароля пользователя: {$#editing_user.login} - {$#editing_user.name}</h1>

    {{include file='_admin/form_errors.phtml'/}}

    <div class='tabs'>

      <ul class="bookmarks">
        <li id='properties_link'><a href="#">Свойства</a></li>
      </ul>

      <div id="tab_properties" class='bookmarks_content'>

        <dl class='required field'>
          <dt>{{label for="password" errorclass='error_label'}}Текущий пароль:{{/label}}</dt>
          <dd>{{input type="text" name="password" title="Текущий пароль" class="input" /}}</dd>
        </dl>

        <dl class='required field'>
          <dt>{{label for="new_password" errorclass='error_label'}}Новый пароль:{{/label}}</dt>
          <dd>{{input type="text" name="new_password" title="Новый пароль" class="input" /}}</dd>
        </dl>

        <dl class='required field'>
          <dt>{{label for="repeat_new_password" errorclass='error_label'}}Подтверждение пароля:{{/label}}</dt>
          <dd>{{input type="text" name="repeat_new_password" title="Подтверждение пароля" class="input" /}}</dd>
        </dl>

      </div>

    </div>

    {{include file='_admin/form_buttons.phtml'/}}

  {{/form}}

{{/wrap}}
