{{wrap with="_cms/popup.phtml" into="content_zone"}}

  <h1 class='delete'>Удалить пользователей</h1>

  {{form id='delete_form' name='delete_form' method='post' runat='server' class="list"}}

    <?php $this->items_to_delete= lmbActiveRecord::findByIds('lmbCmsUser',$this->request->get('ids'));?>

    <table>
    <tr>
      <th class='selector'>{{include file='_cms/selector.phtml'/}}</th>
      <th>Логин</th>
      <th>Имя</th>
    </tr>
    {{list using="{$#items_to_delete}" parity="{$parity}"}}
      {{list:item}}
        <tr class='{$parity}'>
          <td>{{input type='checkbox' name='ids[]' value='{$item.id}' checked='true'/}}</td>
          <td>{$item.login}</td>
		  <td>{$item.name}</td>
        </tr>
      {{/list:item}}
    {{/list}}
    </table>
	{{include file='_cms/delete_common_elements.phtml'/}}

  {{/form}}
{{/wrap}}