{{wrap with="_cms/page.phtml" into="content_zone"}}
   <div id="header_block">

      <h1>Список пользователей</h1>

      <div class="header_actions">
	      <a href='{{route_url params="action:create" /}}?popup=1' class='create'>Добавить пользователя</a>
      </div>

    </div>

    <div id="content_block">

      <active_record:fetch class_path='limb/cms/src/model/lmbCmsUser' target="users" order="email=ASC" navigator="pager"/>
      <?php $this->users= lmbActiveRecord::find('lmbCmsUser');?>
      {{paginate iterator='$#users' pager='pager' /}}
	    {{include file='_cms/pager.phtml'/}}

      {{form name='list_form' method='post' class='list'}}

        <div class='list_actions'>
          <input type="button" class='button' value="Удалить" onclick='Limb.Form.submitPopup(this.form, "{{route_url params="action:delete" /}}");'/>
        </div>

        <table>
          <tr>
            <th class='selector'>{{include file='_cms/selector.phtml'/}}</th>
            <th>#ID</th>
            <th>Имя</th>
            <th>Логин</th>
            <th>E-mail</th>
            <th>Группа</th>
            <th>Действия</th>
          </tr>
          {{list using='{$#users}' parity='{$Parity}'}}
            {{list:item}}
            <tr class='{$Parity}'>
              <td class='selector'>{{input type='checkbox' name='ids[]' value='{$item.id}' runat='client'/}}</td>
              <td>#{$item.id}</td>
              <td>{$item.name}</td>
              <td>{$item.login}</td>
              <td><a href='mailto:{$item.email}'>{$item.email}</a></td>
              <td>{$item.current_role.name}</td>
              <td class='actions'>
                  <a href='{{route_url params="action:change_password,id:{$item.id}?popup=1" /}}'  title="Сменить пароль"><img src='/shared/cms/images/icon/action/password.gif' width='14' height='16' alt='Сменить пароль'/></a>
                  <a href='{{route_url params="action:edit,id:{$item.id}?popup=1" /}}'  title="Редактировать"><img src='/shared/cms/images/icon/action/edit.gif' width='16' height='17'  alt='Редактировать' /></a>
				          <a href='{{route_url params="action:delete?popup=1&ids[]={$item.id}" /}}'  title="Удалить"><img src='/shared/cms/images/icon/action/delete.gif' width='14' height='17'  alt='Удалить' /></a>
              </td>
            </tr>
            {{/list:item}}
          {{/list}}
        </table>

        <div class='list_actions'>
          <input type="button" class='button' value="Удалить" onclick='Limb.Form.submitPopup(this.form, "{{route_url params="action:delete" /}}");'/>
        </div>

      {{/form}}

    </div>

{{/wrap}}
