{{template name="object_action"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $item = isset($item) ? $item : false;
    $is_link = isset($is_link) ? $is_link : false;
    $icon = isset($icon) ? $icon : "add";
  ?>
  <a href='{{route_url params="controller:{$controller},action:{$action},id:{$item.id}"/}}' title="{$title}" class="thickbox"><img src='/shared/cms/images/icons/{$icon|default:"add"}.png'/> <? if($is_link) echo $title; ?></a>
{{/template}}

{{template name="object_action_edit"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : 'Редактировать';
    $icon = isset($icon) ? $icon : "pencil";
  ?>
  <a href='{{route_url params="controller:{$controller},action:edit,id:{$item.id}"/}}' title="{$title|default:'Редактировать'}" class="thickbox"><img src='/shared/cms/images/icons/{$icon|default:"pencil"}.png'/> <? if($is_link) echo $title; ?></a>
{{/template}}

{{template name="object_action_delete"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : 'Удалить';
    $icon = isset($icon) ? $icon : "delete";
  ?>
  <a href='#' onclick="if(confirm('Вы действительно желаете удалить выбранный объект?')) {jQuery.post('{{route_url params='controller:{$controller},action:delete'/}}', {ids:{$item.id}}, function(){document.location.reload()})}"  title="{$title|default:'Удалить'}"><img src='/shared/cms/images/icons/{$icon|default:"delete"}.png'/> <? if($is_link) echo $title; ?></a>
{{/template}}

{{template name="object_action_publish"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : 'Показать';
    $icon = isset($icon) ? $icon : "lightbulb";
  ?>
  <a href='{{route_url params="controller:{$controller},action:publish,id:{$item.id}"/}}' title="{$title|default:'Показать'}" class="publish thickbox"><img src='/shared/cms/images/icons/{$icon|default:"lightbulb"}.png'/> <? if($is_link) echo $title; ?></a>
{{/template}}

{{template name="object_action_unpublish"}}
  <?
    $controller = isset($controller) ? $controller : lmbToolkit::instance()->getDispatchedController()->getName();
    $is_link = isset($is_link) ? $is_link : false;
    $title = isset($title) ? $title : 'Скрыть';
    $icon = isset($icon) ? $icon : "lightbulb_off";
  ?>

  <a href='{{route_url params="controller:{$controller},action:unpublish,id:{$item.id}"/}}' title="{$title|default:'Скрыть'}" class="unpublish thickbox"><img src='/shared/cms/images/icons/{$icon|default:"lightbulb_off"}.png'/> <? if($is_link) echo $title; ?></a>
{{/template}}