<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<html>
<head>
  <title>Панель управления :: Восстановление пароля</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
  <link rel=stylesheet type="text/css" href="/shared/cms/styles/cp.css" />
  <link rel=stylesheet type="text/css" href="/shared/cms/styles/cp.css" />
  <!--[if IE]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie.css" /><![endif]-->
  <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie6.css" /><![endif]-->
</head>
<body id='login_form'>

  <div id="login_form_wrapper">

    <form method="post" id='password_form' runat='server'>

        <div id="logo_limb">
          <a href="http://limb-project.com"><img src="/shared/cms/images/logo.limb.png" alt='LIMB'/></a>
        </div>

        <div id="form_body">

          <h1>Восстановление пароля</h1>

          <dl class='field'>
            <dt><label for='email'>Email:</label></dt>
            <dd>
              <input type="text" name="email" id="email" value="" title="Email" class='input'/>
              <input type='submit' class='button' name='submitted' value="OK" />
            </dd>
          </dl>

          <a href="/user/login" class="forgot_password_link">Отмена</a>

          <div id="forgot_password_comment">После отправки данной формы вы получите письмо с новым паролем и ссылкой для его активации</div>

          {{include file='_admin/notify_zone.phtml'/}}

        </div>

    </form>

    <div class='shadow_bottom'><div class='left'></div><div class='center'></div><div class='right'></div></div>
    <div class='shadow_left'><div class='top'></div><div class='center'></div></div>
    <div class='shadow_right'><div class='top'></div><div class='center'></div></div>

  </div>

</body>
</html>

