<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<? $this->static_files_version = lmb_env_get('CMS_STATIC_FILES_VERSION'); ?>
<html>
<head>
  <title>Панель управления</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp.css?{$#static_files_version}" />
  <!--[if IE]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie.css?{$#static_files_version}" /><![endif]-->
  <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/shared/cms/styles/cp_ie6.css?{$#static_files_version}" /><![endif]-->
  <link rel="stylesheet" type="text/css" href="/shared/cms/styles/thickbox.css?{$#static_files_version}" />
  {{slot id='header_zone' /}}
  <style type="text/css">
    {{slot id='css_zone' /}}
  </style>
</head>
<body>
  <div id="wrapper">

    {{include file='_admin/notify_zone.phtml'/}}

    <div id='admin_panel'>
      <a href="/admin"><img src="/shared/cms/images/logo.limb.png"  alt='LIMB' id='logo_project'/></a>
      <ul id='user_data'>
        <li>{$#toolkit.cms_user.login} [ {$#toolkit.cms_user.name} ]</li>
        <li><a href='/user/logout' class='logout'>Выйти</a></li>
      </ul>
    </div>

    <div id='main_col'>
      <div id="main_col_content">
        {{slot id='content_zone'/}}
      </div>
    </div>

    <div id='sidebar'>
      <?php
        lmb_require('limb/cms/src/fetcher/lmbCmsAdminNavigationFetcher.class.php');
        $this->navigation=new lmbCmsAdminNavigationFetcher();
        $this->navigation=$this->navigation->fetch();
      ?>
      <dl id='main_menu'>
      {{list:list id='navigation' using='$#navigation'}}
        {{list:item}}
        <dt class='{$item.id}'><img src='{$item.icon}'/> {$item.title} </dt>
        <dd>
          {{list:list using='$item.children' as="$sub_item"}}
            <ul>
              {{list:item}}
              <li>
                <img src='{$sub_item.icon}'/> <a href='{$sub_item.url}'>{$sub_item.title}</a>
              </li>{{/list:item}}
            </ul>
          {{/list:list}}
        </dd>
        {{/list:item}}
      {{/list:list}}
      </dl>
      {{slot id='context_help'/}}
    </div>

  </div>

  <script src="<? echo lmb_env_get('JQUERY_FILE_URL'); ?>?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb.js?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb/url.js?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb/flash.js?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb/window.js?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb/forms.js?{$#static_files_version}"></script>
  <script src="/shared/js/js/limb/form_elements.js?{$#static_files_version}"></script>
  <script src="/shared/cms/js/tabs.js?{$#static_files_version}"></script>
  <script src="/shared/cms/js/auto_tabs.js?{$#static_files_version}"></script>
  <script src="/shared/cms/js/thickbox.js?{$#static_files_version}"></script>
  <script src="/shared/cms/js/cp.js?{$#static_files_version}"></script>
  {{slot id='js_include'/}}

  <script type="text/javascript">
    {{slot id='js'/}}

    jQuery(window).ready(function()
    {
      {{slot id='js_ready'/}}

      thickboxInit();

      function thickboxInit()
      {
        jQuery("a.thickbox").each(function()
        {
          if(this.href.indexOf('TB_iframe') > 0)
            return;

          var sep = (this.href.indexOf('?') > 0) ? '&' : '?';
          this.href = this.href + sep + 'TB_iframe=true&width=640&height=480';
        });

        tb_init('a.thickbox');                                    //pass where to apply thickbox
        imgLoader = new Image();                                  // preload image
        imgLoader.src = "/shared/cms/images/icons/loading.gif";
      }
    });
  </script>

</body>
</html>

