<div class='tabs'>

  <ul>
    <li id='properties'><a href="#">Свойства</a></li>
  </ul>

  <div id="tab_properties" class='bookmarks_content'>

    <div class="left_side">
      {{include file='admin_user/common_fields.phtml'/}}
    </div>

    <div class="right_side">

      <div class='required field'>
        {{label for="password" errorclass='error_label'}}Пароль:{{/label}}
        {{input name="password" type="password" title="Пароль"/}}
      </div>

      <div class='required field'>
        {{label for="repeat_password" errorclass='error_label'}}Подтверждение пароля:{{/label}}
        {{input name="repeat_password" type="password" title="Подтверждение пароля"/}}
      </div>

    </div>

  </div>

</div>
