{{wrap with="admin_page_layout.phtml"}}
  {{into slot="content_zone"}}

    {{include file="_admin_object/actions.phtml"/}}

    <div id="header">
      <h1><?php if(!$this->is_root) : ?>Страница &laquo;{$#item.title}&raquo; <?php else : ?>  Список документов<?php endif?></h1>
      
      {{include file='_widgets/cms_document_breadcrumbs.phtml' item="{$#item}" base_path="/admin_document/display/" link_field='id' root_path='/admin_document/' /}} 
      <div class="header_actions">
        <?php if(!$this->is_root) : ?>

                <a href='{$#item.uri}' title="Просмотр" target="_blank"><img src='/shared/cms/images/icons/page.png'/></a>
        {{apply template="object_action_edit" item="{$#item}" icon="page_edit"/}}
        <? if($this->item->getIsPublished()): ?>
          {{apply template="object_action_unpublish" item="{$#item}" icon="page_red"/}}
        <?  else:  ?>
          {{apply template="object_action_publish" item="{$#item}" icon="page_green"/}}
        <? endif; ?>
        {{apply template="object_action_delete" item="{$#item}"/}}
        <br/><br/>

        {{apply template="object_action" item="{$#item}" action="create_child" is_link="true" title="Добавить дочерний документ" icon="page_add"/}}

        <?  else:  ?>
        {{apply template="object_action" action="create" title="Создать документ" icon="page_add" is_link="true"/}}
        <? endif ?>
      </div>
    </div>

    <div id="body">
      {{include file='_admin/pager.phtml' items="{$#items}"/}}
      {{include file='admin_document/include/items_list.phtml' items="{$#items}"/}}
    </div>

  {{/into}}
{{/wrap}}
