<?php
  $limit = intval(isset($per_page) ? $per_page : 20);
?>
{{paginate iterator='$items' pager='pager' limit="{$limit}"/}}

{{pager id="pager"}}
  <?php  if($total_pages > 1){ ?>
    <div class='pager'>
      {{pager:first}}<a href="{$href}"><img src="/shared/cms/images/button/arrow_first.gif"  width='18' height='17' alt='&#171;'/></a>{{/pager:first}}
      {{pager:prev}}<a href="{$href}"><img src="/shared/cms/images/button/arrow_prev.gif"  width='18' height='17' alt='&#60;'/></a>{{/pager:prev}}
      {{pager:list}}
        {{pager:section}}<a href="{$href}">[{$section_begin_page}..{$section_end_page}]</a>{{/pager:section}}
        {{pager:current}}<b>{$number}</b>{{/pager:current}}
        {{pager:number}}<a href="{$href}">{$number}</a>{{/pager:number}}
        {{pager:separator}} {{/pager:separator}}
      {{/pager:list}}
      {{pager:next}}<a href="{$href}"><img src="/shared/cms/images/button/arrow_next.gif"  width='18' height='17' alt='&#62;'/></a>{{/pager:next}}
      {{pager:last}}<a href="{$href}"><img src="/shared/cms/images/button/arrow_last.gif"  width='18' height='17' alt='&#187;'/></a>{{/pager:last}}
    </div>
  <? } ?>
{{/pager}}
