{{template name="object_action"}}
  <a href='{{route_url params="action:{$action},id:{$item.id}"/}}' title="{$title}" class="thickbox">
    <img src='/shared/cms/images/icons/{$icon}.png' title="{$title}"/>
  </a>
{{/template}}

{{template name="object_action_edit"}}
  <?php $title = isset($title) ? $title : lmb_i18n('Edit', 'cms'); ?>
  <a href='{{route_url params="action:edit,id:{$item.id}"/}}' title="{$title}" class="thickbox">
    <img src='/shared/cms/images/icons/{$icon|default:"pencil"}.png' title="$title"/>
  </a>
{{/template}}

{{template name="object_action_delete"}}
  <a href='#' onclick="if(confirm('{{i18n text="Delete item" domain="cms"/}}?')) {jQuery.post('{{route_url params='action:delete'/}}', {ids:{$item.id}}, function(){document.location.reload()})}" title="Delete">
    <img src='/shared/cms/images/icons/page_delete.png'/>
  </a>
{{/template}}