<?php
  $uri = lmbToolkit::instance()->getRequest()->getUri();
  $uri->addQueryItem('sort',$field);
  $uri->addQueryItem('direction','asc');
  $title = lmb_i18n('Sort ascending', 'cms');
?>
<a href="{$uri->toString()}" title="{$title}">
  <img src="/shared/cms/images/icons/arrow_down.png" alt="{$title}"/>
</a>
<?php
  $uri = lmbToolkit::instance()->getRequest()->getUri();
  $uri->addQueryItem('sort',$field);
  $uri->addQueryItem('direction','desc');
  $title = lmb_i18n('Sort descending', 'cms');
?>
<a href=" echo $uri->toString();  ?>" title="{$title}">
  <img src="/shared/cms/images/icons/arrow_up.png" alt="{$title}"/>
</a>
