{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}
    {{form id='object_form' name='user_form' method='post' enctype="multipart/form-data"}}
     <?php if($this->parent->getId() == lmbCmsDocument :: findRoot()->getId()) : ?>
      <h1>Создание документа</h1>
      <?php else : ?>
      <h1>Добавление дочерней страницы для &laquo;{$#parent.title}&raquo;</h1>
      <?php endif ?>
      {{include file='admin_document/include/form_fields.phtml'/}}
    {{/form}}
{{/wrap}}
