{{include file='_admin/form_errors.phtml'/}}

<div class='tabs'>

  <ul>
    <li id='properties'><a href="#">Свойства</a></li>
  </ul>

  <div id="tab_properties">

    <dl class="required field">
      <dt><label for="url">Url:</label></dt>
      <dd>{{input type="text" name="url" id="url" title="URL"/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="title">Title:</label></dt>
      <dd>{{input type="text" name="title" id="title" title="Title"/}}</dd>
    </dl>

    <dl class="field">
      <dt>{{label for="keywords"}}Keywords:{{/label}}</dt>
      <dd>{{textarea type="text" name="keywords" id="keywords" title="Keywords"}}{{/textarea}}</dd>
    </dl>

    <dl class="field">
      <dt>{{label for="description"}}Description:{{/label}}</dt>
      <dd>{{textarea name="description" id="description" title="Description"/}}</dd>
    </dl>

  </div>

</div>

{{include file='_admin/form_buttons.phtml'/}}
