{{wrap with="admin_page_layout.phtml"}}
  {{into slot="content_zone"}}

    <div id="header">
      <h1>Текстовые блоки</h1>
    </div>

    <div id="body">

      {{list using='{$#blocks}' parity='{$parity}'}}

        {{include file="_admin_object/actions.phtml"/}}

        <div class="list">
          <table>
            <tr>
              <th>Статус</th>
              <th>Заголовок</th>
              <th width="60%">Содержимое</th>
              <th>Действия</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>
              <td>
                <?
                if ($item['exists'])
                {?>
                  <img src='/shared/cms/images/icons/flag_green.png' alt="есть" title="Используется установленное пользователем значение"/>
              <?}
                else
                {?>
                  <img src='/shared/cms/images/icons/flag_red.png' alt="нет" title="Используется значение по-умлочанию"/>
              <?}?>
              </td>
              <td>{$item.title}</td>
              <td><b>ID</b>: {$item.identifier}<br/>
              <b>Текст</b>: {$item.content|striptags|i18n_clip:'150'} ...
              </td>
              <td class='actions'>
                <a href='{{route_url params="action:preview,id:{$item.identifier}"/}}' title="Предварительный просмотр" class="thickbox"><img src='/shared/cms/images/icons/zoom.png' alt="Предпросмотр"/></a>
                <a href='{{route_url params="action:edit,id:{$item.identifier}"/}}' title="Редактирование" class="thickbox"><img src='/shared/cms/images/icons/table_edit.png' alt="Редактирование"/></a>
              </td>
              </tr>
            {{/list:item}}
            {{list:empty}}
              <div class="empty_list">Текстовые блоки отсутствуют</div>
            {{/list:empty}}
          </table>
        </div>

      {{/list}}

    </div>

  {{/into}}
{{/wrap}}
