{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}

<h1>Редактировать текстовый блок &laquo;{$#item.title}&raquo; ({$#item.identifier})</h1>

  {{form id='object_form' name='object_form' method='post' enctype="multipart/form-data"}}

    {{include file='_admin/form_errors.phtml'/}}

    <div class='tabs'>

      <ul>
        <li id='properties'><a href="#">Свойства</a></li>
      </ul>

      <div id="tab_properties">

        {{wysiwyg id='content' name='content' width='100%' height='310' title="Контент"/}}

      </div>

    </div>

    {{include file='_admin/form_buttons.phtml'/}}

  {{/form}}

{{/wrap}}
