{{form:errors to='$fields_errors'/}}

{{list using='$fields_errors' as="$error"}}
  <div class="message_error">
    <a class='show_hidden'><img src="/shared/cms/images/button/show_hidden.gif"  width='11' height='9' alt='показать/скрыть'/></a>
    <b class='title'>Следующие поля содержали ошибки</b>
    <span class='border_h'><span class='l'></span><span class='r'></span></span>
    <div class="border_c">
      <div class="content">
        <ol>
  {{list:item}}
    <li><font color="red">{$error.message}</font></li>
  {{/list:item}}
       </ol>
      </div>
    </div>
    <span class='border_b'><span class='l'></span><span class='r'></span></span>
  </div>
{{/list}}