<?php
  lmb_require('limb/cms/src/fetcher/lmbCmsAdminNavigationFetcher.class.php');
  $this->navigation=new lmbCmsAdminNavigationFetcher();
  $this->navigation=$this->navigation->fetch();
?>
<dl id='main_menu'>
  {{list:list id='navigation' using='$#navigation'}}
  {{list:item}}
  <dt class='{$item.id}'><span>{$item.title}</span></dt>
  <dd>{{list:list using='$item.children' as="$sub_item"}}<ul>{{list:item}}<li><a href='{$sub_item.url}'>{$sub_item.title}</a></li>{{/list:item}}</ul>{{/list:list}}</dd>
  {{/list:item}}
  {{/list:list}}
</dl>
