{{flashbox}}
{{list using="{$flashbox}"}}
  <div class='notify_zone'>
    <span class='close' onclick='jQuery(".notify_zone").slideUp()'>Закрыть</span>
  {{list:item}}
    <?php if($item['is_error']) $class_name='error'; else $class_name='message'; ?>
      <span class='{$class_name}'>{$item.message}</span>
	  {{list:glue step="1"}}<br />{{/list:glue}}
  {{/list:item}}
  </div>
{{/list}}
{{/flashbox}}