{{pager id="pager" items="20" pages_per_section="5"}}
<div class='pager'>
{{pager:first}}<a href="{$href}" class="arr"><img src="/shared/cms/images/button/arrow_first.gif"  width='18' height='17' alt='&#171;'/></a>{{/pager:first}}
{{pager:prev}}<a href="{$href}" class="arr"><img src="/shared/cms/images/button/arrow_prev.gif"  width='18' height='17' alt='&#60;'/></a>{{/pager:prev}}
{{pager:list}}
{{pager:section}}<a href="{$href}">[{$section_begin_page}..{$section_end_page}]</a>{{/pager:section}}
{{pager:current}}<b>{$number}</b>{{/pager:current}}
{{pager:number}}<a href="{$href}">{$number}</a>{{/pager:number}}
{{pager:separator}} {{/pager:separator}}
{{/pager:list}}
{{pager:next}}<a href="{$href}" class="arr"><img src="/shared/cms/images/button/arrow_next.gif"  width='18' height='17' alt='&#62;'/></a>{{/pager:next}}
{{pager:last}}<a href="{$href}" class="arr"><img src="/shared/cms/images/button/arrow_last.gif"  width='18' height='17' alt='&#187;'/></a>{{/pager:last}}
</div>
{{/pager}}
