<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<html>
<head>
  <title>Панель управления</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>

  {{include file='_cms/styles.phtml'/}}
  {{include file='_cms/js.phtml'/}}
</head>
<body>
<div id="wrapper">

  <div id='admin_panel'>
    <img src="/shared/cms/images/limb_admin.gif"  width='94' height='25' alt='LIMB' id='logo_project'/>
    {{include file='_cms/user_data.phtml'/}}
  </div>

  <div id='container'>
    <div id="content">
      {{slot id='content_zone'/}}
    </div>
  </div>

  <div id='sidebar'>
    {{include file='_cms/menu.phtml'/}}
  </div>

</div>

</body>
</html>

