<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
{{include file='_cms/styles.phtml'/}}
{{include file='_cms/js.phtml'/}}
</head>
<body class='popup'>
  {{slot id='icon'/}}
  {{slot id='title'/}}
  {{slot id='content_zone'/}}
</body>
</html>
